Updated build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,7 +34,7 @@ jobs:
           echo "
             gitlab.url = https://gitlab.com/api/v4/projects/41661215/packages/maven/
             gitlab.auth.header.name = Private-Token
-            gitlab.auth.header.value = $ {{ secrets.GITLAB_AUTH_HEADER_VALUE }}
+            gitlab.auth.header.value = ${{ secrets.GITLAB_AUTH_HEADER_VALUE }}
           
             github.url = https://maven.pkg.github.com/${{ github.REPOSITORY }}
             github.auth.username = L1ghtDream
@@ -42,8 +42,8 @@ jobs:
           " > ~/.gradle/gradle.properties
           
           
-          gradle publishGitHub ||  echo "Failed to publish to GitHub"
-          gradle publishGitLab ||  echo "Failed to publish to GitLab"
+          gradle publishGitHub || echo "Failed to publish to GitHub"
+          gradle publishGitLab || echo "Failed to publish to GitLab"
           
           echo "HERE"
           
